//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheBien
    {
        public string MaSP { get; set; }
        public string MaNL { get; set; }
        public int SoLuong { get; set; }
    
        public virtual NguyenLieu NguyenLieu { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
