//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QUANLYCUAHANGEntities : DbContext
    {
        public QUANLYCUAHANGEntities()
            : base("name=QUANLYCUAHANGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CheBien> CheBiens { get; set; }
        public virtual DbSet<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DbSet<DoanhThu> DoanhThus { get; set; }
        public virtual DbSet<DonHangMua> DonHangMuas { get; set; }
        public virtual DbSet<LichLamViec> LichLamViecs { get; set; }
        public virtual DbSet<MaGiamGia> MaGiamGias { get; set; }
        public virtual DbSet<NguyenLieu> NguyenLieux { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<NguyenLieuCuaSanPham> NguyenLieuCuaSanPhams { get; set; }
        public virtual DbSet<NhanVienHienTai> NhanVienHienTais { get; set; }
        public virtual DbSet<SP_Da_Ban> SP_Da_Ban { get; set; }
    
        [DbFunction("QUANLYCUAHANGEntities", "sf_DanhSach_LamViecNgayCa")]
        public virtual IQueryable<sf_DanhSach_LamViecNgayCa_Result> sf_DanhSach_LamViecNgayCa(Nullable<System.DateTime> ngay, Nullable<int> ca)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var caParameter = ca.HasValue ?
                new ObjectParameter("ca", ca) :
                new ObjectParameter("ca", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<sf_DanhSach_LamViecNgayCa_Result>("[QUANLYCUAHANGEntities].[sf_DanhSach_LamViecNgayCa](@ngay, @ca)", ngayParameter, caParameter);
        }
    
        [DbFunction("QUANLYCUAHANGEntities", "sf_DanhSach_LLVTrongNgay")]
        public virtual IQueryable<sf_DanhSach_LLVTrongNgay_Result> sf_DanhSach_LLVTrongNgay(Nullable<System.DateTime> ngay)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<sf_DanhSach_LLVTrongNgay_Result>("[QUANLYCUAHANGEntities].[sf_DanhSach_LLVTrongNgay](@ngay)", ngayParameter);
        }
    
        [DbFunction("QUANLYCUAHANGEntities", "sf_nv_LocNhanVienTheoChucVu")]
        public virtual IQueryable<sf_nv_LocNhanVienTheoChucVu_Result> sf_nv_LocNhanVienTheoChucVu(Nullable<byte> chucVu)
        {
            var chucVuParameter = chucVu.HasValue ?
                new ObjectParameter("chucVu", chucVu) :
                new ObjectParameter("chucVu", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<sf_nv_LocNhanVienTheoChucVu_Result>("[QUANLYCUAHANGEntities].[sf_nv_LocNhanVienTheoChucVu](@chucVu)", chucVuParameter);
        }
    
        [DbFunction("QUANLYCUAHANGEntities", "sf_nv_LocNhanVienTheoGioiTinh")]
        public virtual IQueryable<sf_nv_LocNhanVienTheoGioiTinh_Result> sf_nv_LocNhanVienTheoGioiTinh(Nullable<byte> gioiTinh)
        {
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("gioiTinh", gioiTinh) :
                new ObjectParameter("gioiTinh", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<sf_nv_LocNhanVienTheoGioiTinh_Result>("[QUANLYCUAHANGEntities].[sf_nv_LocNhanVienTheoGioiTinh](@gioiTinh)", gioiTinhParameter);
        }
    
        [DbFunction("QUANLYCUAHANGEntities", "sf_ThongTinDonHang")]
        public virtual IQueryable<sf_ThongTinDonHang_Result> sf_ThongTinDonHang(Nullable<System.DateTime> ngayBatDau, Nullable<System.DateTime> ngayKetThuc)
        {
            var ngayBatDauParameter = ngayBatDau.HasValue ?
                new ObjectParameter("ngayBatDau", ngayBatDau) :
                new ObjectParameter("ngayBatDau", typeof(System.DateTime));
    
            var ngayKetThucParameter = ngayKetThuc.HasValue ?
                new ObjectParameter("ngayKetThuc", ngayKetThuc) :
                new ObjectParameter("ngayKetThuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<sf_ThongTinDonHang_Result>("[QUANLYCUAHANGEntities].[sf_ThongTinDonHang](@ngayBatDau, @ngayKetThuc)", ngayBatDauParameter, ngayKetThucParameter);
        }
    
        public virtual ObjectResult<sp_DanhSach_NhanVienVoiLuong_Result> sp_DanhSach_NhanVienVoiLuong(Nullable<int> min, Nullable<int> max)
        {
            var minParameter = min.HasValue ?
                new ObjectParameter("min", min) :
                new ObjectParameter("min", typeof(int));
    
            var maxParameter = max.HasValue ?
                new ObjectParameter("max", max) :
                new ObjectParameter("max", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DanhSach_NhanVienVoiLuong_Result>("sp_DanhSach_NhanVienVoiLuong", minParameter, maxParameter);
        }
    
        public virtual ObjectResult<sp_DoanhThuNgayTheoThang_Result> sp_DoanhThuNgayTheoThang(Nullable<int> thang)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DoanhThuNgayTheoThang_Result>("sp_DoanhThuNgayTheoThang", thangParameter);
        }
    
        public virtual ObjectResult<sp_ThongTinDonHangTheoSanPham_Result> sp_ThongTinDonHangTheoSanPham(string maSanPham)
        {
            var maSanPhamParameter = maSanPham != null ?
                new ObjectParameter("maSanPham", maSanPham) :
                new ObjectParameter("maSanPham", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongTinDonHangTheoSanPham_Result>("sp_ThongTinDonHangTheoSanPham", maSanPhamParameter);
        }
    }
}
