//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVienHienTai
    {
        public string MaNV { get; set; }
        public string TenNV { get; set; }
        public byte GioiTinh { get; set; }
        public byte LoaiNV { get; set; }
        public Nullable<int> Luong { get; set; }
        public byte ChucVu { get; set; }
    }
}
